- name: "journald: ForwardToSyslog"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regex: "^[#]?ForwardToSyslog"
    line: ForwardToSyslog=yes
    
- name: "journald: Compress"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regex: "^[#]?Compress"
    line: Compress=yes

- name: "journald: Storage"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regex: "^[#]?Storage"
    line: Storage=persistent
 